InjectiveLabs/injective-dex

- assets/css/components/_inputs.scss
- components/elements/card-table-wrap.vue
- components/inputs/input.vue
- components/inputs/search.vue
- components/partials/history/trades.vue
- locales/en.ts
- types/derivatives.ts
- types/spot.ts
> feat: filter trade by market ticker

- app/services/bank.ts
- app/services/ibc.ts
- app/services/tokens.ts
- app/singletons/IbcConsumer.ts
- components/partials/wallet/balances/balance.vue
- components/partials/wallet/balances/index.vue
- package.json
- store/bank.ts
- store/token.ts
- types/bank.ts
- yarn.lock
> fix: ibc assets not reflecting on wallet page balances

- app/services/derivatives.ts
- components/partials/portfolio/open-positions.vue
- locales/en.ts
- plugins/store.ts
- store/derivatives.ts
> feat: close all positions

- components/partials/portfolio/holdings/index.vue
- components/partials/wallet/balances/balance.vue
- components/partials/wallet/balances/index.vue
- types/bank.ts
- resolves #359 
- ### Wallet page - balance table
- ### Portfolio page - sub account table
> feat: sort portfolio value base on USD

- app/utils/constants.ts
- components/elements/dropdown.vue
- components/partials/common/orderbook/aggregation-selector.vue
- components/partials/derivatives/orderbook.vue
- components/partials/derivatives/orderbook/index.vue
- components/partials/derivatives/orderbook/order-book.vue
- components/partials/derivatives/orderbook/record.vue
- components/partials/spot/orderbook.vue
- components/partials/spot/orderbook/index.vue
- components/partials/spot/orderbook/order-book.vue
- components/partials/spot/orderbook/record.vue
- types/index.ts
- resolves #28 
https://user-images.githubusercontent.com/10151054/140984878-5e05b841-69ea-4ec8-9f7d-26f48f12a7c1.mp4
> feat: minimum price increments for orderbook aggregation

- components/partials/derivatives/orderbook/order-book.vue
- components/partials/spot/orderbook/order-book.vue
- resolves #28 
- more [information](https://github.com/InjectiveLabs/injective-dex/issues/28#issuecomment-966219557) about this issue.
> fix: buy order books price not aggregating properly

- package.json
> Fixed the definition of the prettier script which used to execute infinitely.
- Renamed script `prettier` to `pretty` in _package.json_ 
- Resolves #374
> Fixed the definition of prettier script

- app/utils/constants.ts
- components/partials/common/elements/emp-number.vue
- components/partials/trade-and-earn/campaign.vue
- components/partials/trade-and-earn/current-epoch.vue
- pages/trade-and-earn.vue
- store/token.ts
- tailwind.config.js
- adds USD balance to rewards page INJ allocated rewards and estimated rewards
| Allocated reward | Estimated reward |
|---|---|
| ![image](https://user-images.githubusercontent.com/10151054/142821590-74ea8dda-c6d0-43e2-a5c2-46ce928ee88c.png) | ![image](https://user-images.githubusercontent.com/10151054/142821614-1011cff7-18a5-43d0-b25a-bb40f15389e8.png) |
> feat: add inj usd balance to rewards page

- components/partials/spot/trading/order-details.vue
- resolves FE-3
| Before | After |
|-----|-----|
| ![image](https://user-images.githubusercontent.com/10151054/142997793-207c639e-b120-4afd-a8c3-5b415a64374b.png) | ![image](https://user-images.githubusercontent.com/10151054/142997586-57160f78-5b8a-427f-8942-8c7ca8c20ee2.png) |
> fix: incorrect format on spot limit sell order details

- components/partials/common/markets/market.vue
- resolves #453 
- resolve FE-295
> chore: close market slide out on market click

- components/partials/wallet/transfer-on-chain.vue
- resolves #382 
- resolves FE-296
> feat: allow IBC denoms to be transferrable on wallet page

- app/utils/constants.ts
- components/partials/trade-and-earn/campaign.vue
- components/partials/trade-and-earn/current-epoch.vue
- locales/en.ts
- pages/trade-and-earn.vue
- store/exchange.ts
- store/wallet.ts
Resolves [#FE-337](https://linear.app/injective/issue/FE-337/dex-trade-and-earn-ui-adjustment-for-inj-staking-requirement)
> feat: trade and earn UI update - #FE-337

- components/partials/trade-and-earn/current-epoch.vue
- components/partials/trade-and-earn/previous-rewards.vue
- locales/en.ts
> chore: dmm page copy improvement

- app/data/bridge.ts
- components/elements/allowance.vue
- components/layout/wallet/wallets/ledger/index.vue
- components/partials/modals/bridge/index.vue
- components/partials/portfolio/balances.vue
- components/partials/portfolio/bridge.vue
- components/partials/portfolio/bridge/token-selector/index.vue
- locales/bridge/en.ts
- store/token.ts
- resolves [FE-516](https://linear.app/injective/issue/FE-516/deposits-from-other-chains)
- resolves [FE-517](https://linear.app/injective/issue/FE-517/adds-setting-allowance-ux-on-lite-bridge)
> feat: implement set allowance ux flow on lite bridge

- assets/css/components/_custom.scss
- components/partials/portfolio/balances.vue
- components/partials/portfolio/trading-account-balances/balance.vue
- components/partials/portfolio/trading-account-balances/index.vue
- resolves UST position not reflecting on trading account balance table issue
> fix: ust position not reflecting on trading account balance table

- app/services/account/index.ts
- app/services/account/types.ts
- components/partials/portfolio/balances.vue
- components/partials/portfolio/trading-account-balances/balance.vue
- components/partials/portfolio/trading-account-balances/index.vue
- pages/derivatives/_derivative.vue
- pages/spot/_spot.vue
- types/index.ts
- fix the following issue #601
> fix: portfolio trading account table not sorted correctly

- app/utils/async.ts
- components/partials/activity/derivatives/index.vue
- components/partials/activity/derivatives/orders.vue
- components/partials/activity/positions/index.vue
- components/partials/activity/positions/positions.vue
- components/partials/activity/spot/index.vue
- components/partials/activity/spot/orders.vue
- components/partials/common/derivatives/position.vue
- components/partials/derivatives/orders.vue
- components/partials/spot/orders.vue
- locales/activity/en.ts
- store/activity.ts
- store/app.ts
- store/derivatives.ts
- store/spot.ts
- implements a fix to resolve #609
> feat: set up streaming on activity derivative and spot page

- app/streams/derivatives.ts
- app/streams/spot.ts
- components/partials/activity/positions/positions.vue
- components/partials/banners/welcome.vue
- components/partials/portfolio/balances.vue
- store/account.ts
- store/derivatives.ts
- store/spot.ts
- set up subaccount balance and positions streaming on portfolio page
- resolve #592
> feat: setup-streaming-on-portfolio-page

- components/partials/modals/bridge/confirm.vue
About this PR: resolve https://github.com/InjectiveLabs/injective-dex/issues/687
> fix: change precision from 8 digits to 4 digits

- locales/bridge/en.ts
About this PR: resolve https://github.com/InjectiveLabs/injective-dex/issues/685
fix wording
> chore: fix wording

- app/data/market.ts
- app/utils/market.ts
- components/elements/empty-list.vue
- components/elements/sortable-header-item.vue
- components/elements/table-body.vue
- components/elements/table-header.vue
- components/partials/common/markets/markets.vue
- components/partials/markets/index.vue
- components/partials/markets/market-row.vue
- layouts/default.vue
- locales/market/en.ts
- resolves #689
- figma [design](https://www.figma.com/file/qJtXzfX9nzh0c7yA6G9iI3/Injective-DEX?node-id=3876%3A84466)
- ### 375px
- ### 640px
- ### 768px
- ### 1280px
> feat: standalone markets page mobile responsiveness

- app/utils/market.ts
- components/elements/sortable-header-item.vue
- components/partials/common/market-selection/market-type-selector.vue
- components/partials/common/market-selection/markets-table-row.vue
- components/partials/common/market-selection/markets-table.vue
- components/partials/common/market/last-traded-price-and-change.vue
- components/partials/markets/filters/market-category-selector.vue
- components/partials/markets/filters/market-quote-selector.vue
- components/partials/markets/filters/market-type-selector.vue
- components/partials/markets/index.vue
- components/partials/markets/market-card.vue
- components/partials/markets/market-row.vue
- package.json
- plugins/store.ts
- store/account.ts
- store/app.ts
- types/index.ts
- yarn.lock
> Feat: markets watchlist business logic

- components/partials/markets/overview.vue
- components/trading-view/datafeed/helpers.ts
- components/trading-view/datafeed/history-provider.ts
> chore: round trading chart bars timestamp base on interval settings

- components/partials/common/derivatives/position-table.header.vue
- components/partials/portfolio/trading-account-balances/balances.vue
- locales/portfolio/en.ts
- locales/trade/en.ts
> feat: portfolio page trading account balance table add only margin filter

- app/data/market.ts
- app/utils/market.ts
- components/partials/home/markets/index.vue
- components/partials/home/markets/market-deprecated.vue
- components/partials/home/markets/markets-table.vue
- components/partials/markets/index.vue
- components/partials/modals/market-deprecated.vue
- components/partials/modals/market-untradable.vue
- locales/en.ts
- pages/derivatives/_derivative.vue
- pages/market/_market.vue
- pages/markets.vue
- pages/spot/_spot.vue
- routes.config.js
- store/exchange.ts
- types/enums.ts
- types/index.ts
- resolves #790 
- figma [design](https://www.figma.com/file/qJtXzfX9nzh0c7yA6G9iI3/Injective-DEX?node-id=4712%3A14840)
> feat: implement untradable market modal ux

- components/inputs/input.vue
- types/index.ts
- resolves #704 
https://www.loom.com/share/40918c7240ec48b4ad8e3b3604a33dd0
> chore: enhance input UX

- components/partials/derivatives/trading/order-details-market.vue
- components/partials/derivatives/trading/trade.vue
- components/partials/spot/trading/order-details-market.vue
- components/partials/spot/trading/trade.vue
- locales/trade/en.ts
- resolves #746 
| Spot | Derivative |
|------|-----------|
| <img width="373" alt="image" src="https://user-images.githubusercontent.com/10151054/168879690-0f35def8-3857-4e39-9440-ca834300a563.png"> | <img width="375" alt="image" src="https://user-images.githubusercontent.com/10151054/168879451-a8fbc866-a9f3-4848-be79-9adbb1f6e9b6.png"> |
> feat: spot and derivative market order details calculate total using average price

- components/partials/activity/positions/funding-payments.vue
- components/partials/common/derivatives/mobile-funding-payment.vue
- locales/trade/en.ts
- resolves #753 
- figma [design](https://www.figma.com/file/qJtXzfX9nzh0c7yA6G9iI3/Injective-DEX?node-id=4217%3A10896)
> feat: responsify history funding payments table

- app/data/market.ts
- app/utils/market.ts
- components/partials/markets/filters/index.vue
- routes.config.js
- types/enums.ts
> chore: delist luna ust huahua usdt markets

- components/partials/convert/convert-details.vue
- components/partials/convert/index.vue
- components/partials/modals/bridge/index.vue
- components/partials/portfolio/bridge/token-selector/select.vue
This PR fixes the following issues for swaps:
1. The rate shown for quote -> base is incorrect.
2. The token selector used in bridge is not respecting the amount of decimal places shown in the balance.
> Minor swaps fixes

- app/utils/constants.ts
- components/elements/popper-box.vue
- components/inputs/input.vue
- components/partials/convert/advanced-settings.vue
- components/partials/convert/convert-details.vue
- components/partials/convert/index.vue
- components/partials/convert/types.ts
- components/partials/portfolio/bridge/token-selector/select.vue
- pages/convert/_convert.vue
- yarn.lock
This PR partially cleans up the new Swap/Convert feature by removing unused code and moving things from the main index file to other components. Unfortunately the `convert/index.vue` file is still too big imo, so I will try to resolve that in subsequent PR's.
> Minor bug fixes & clean up for swaps

- components/partials/derivatives/trading/order-details-market.vue
- components/partials/derivatives/trading/order-details.vue
- components/partials/derivatives/trading/trade.vue
- components/partials/spot/trading/order-details-market.vue
- components/partials/spot/trading/order-details.vue
- components/partials/spot/trading/trade.vue
This PR resolves #866 by removing special handling for markets with negative maker fee
> fix: Also apply taker fee discount to markets with negative maker fee

- .github/workflows/deploy.yml
> chore: enable maintenance mode
