- app/services/portfolio.ts
- components/partials/portfolio/open-orders.vue
- components/partials/portfolio/open-positions.vue
- plugins/store.ts
- store/portfolio.ts
- resolves #340 
- also added a fix - resolving `close all position` trying to close unavailable market positions i.e. `GRT/USDT` (this should be a Testnet specific issue)
> fix: cancel all derivative orders not working

- app/services/derivatives.ts
- app/services/spot.ts
- components/partials/derivatives/orderbook/order-book.vue
- components/partials/spot/orderbook/order-book.vue
- resolves multiple order-book aggregation filtering regression issues:
-  [buy orders wrong sorting](https://discord.com/channels/739552603322450092/750697249129889874/907978802074878023)
- [btc pairing markets showing NaN on orderbook](https://discord.com/channels/739552603322450092/750697249129889874/907981060288172082)
> fix: order book aggregation filtering regression issues

- assets/css/components/_inputs.scss
- components/partials/derivatives/trading/order-leverage.vue
> Fixed width and added some padding to the leverage text component.
- Increased the width of the leverage box
- Slightly increased  right and top padding for `x` to level it with text
- Resolves #366 
`Earlier`
`Modified`
> Fixed leverage box appearance

- app/services/derivatives.ts
- app/services/spot.ts
- components/partials/common/orderbook/aggregation-selector.vue
- components/partials/derivatives/orderbook.vue
- components/partials/derivatives/orderbook/order-book.vue
- components/partials/derivatives/orderbook/record.vue
- components/partials/spot/orderbook.vue
- components/partials/spot/orderbook/order-book.vue
- components/partials/spot/orderbook/record.vue
- resolves #384 
- the new changes should be dynamic enough to support scaling base on minPriceTickSize in the following format:
- **0.1** -> `0.1, 1, 10, 1000`
- **0.01** -> `0.01, 0.1, 1, 10`
- **0.001** -> `0.001, 0.01, 0.1, 1`
- do note testing this implementation will testnet and devnet will not be accurate as the minPriceTickSize for BTC is set to 0.001. I've manually override the minPriceTickSize and the implementation works as designed (screenshots attached below).
- ### `0.001` minPriceTickSize:
- ### `0.1` minPriceTickSize:
> fix: orderbook price aggregations not base on minPriceTickSize

- components/partials/trade-and-earn/markets-info/boosted.vue
- hardcodes the AXS/USDT marker multiplier on the rewards page to zero.
- note that this PR will only hardcode the FE reflection of the maker rate on the rewards page, it does not alter any other logic related to the trading rewards implementation.
> chore: hardcode axs/usdt reward maker multiplier to zero

- app/services/derivatives.ts
- app/services/spot.ts
- components/partials/common/orderbook/aggregation-selector.vue
- components/partials/derivatives/orderbook/record.vue
- components/partials/spot/orderbook/record.vue
- resolves #402 
- ### Tested the implementation using ZRX on a `10` and `1` aggregate, manually enabled `10` for testing on my local machine.
|Aggregate by 0.1 | Aggregate by 1 | Aggregate by 10 |
|----|----|----|
| ![image](https://user-images.githubusercontent.com/10151054/142581442-1da08de6-da44-4aab-8fe4-5f167e7f76cc.png) | ![image](https://user-images.githubusercontent.com/10151054/142599652-dd5e20cd-4104-4ba4-ade3-1e6328541e99.png) | ![image](https://user-images.githubusercontent.com/10151054/142599770-b607e223-a19d-453b-aa9f-39cfe4dc2a1a.png) |
> fix: order book aggregated price level showing 0 price issue

- components/partials/spot/trading/order-details-market.vue
- resolves #421
- updates spot market order details format to follow derivative order details format
- ### Before
| buy order details | sell order details |
|----|----|
| ![image](https://user-images.githubusercontent.com/10151054/142828594-615b2e93-2239-4714-89a4-3da63bb25eab.png) | ![image](https://user-images.githubusercontent.com/10151054/142828635-b8939b0f-daa2-4110-ab06-23af48639e69.png) |
- ### After
| buy order details | sell order details |
|----|----|
| ![image](https://user-images.githubusercontent.com/10151054/142828391-936840f0-2e35-49bc-aa3b-34831fe211ad.png) | ![image](https://user-images.githubusercontent.com/10151054/142828433-f584ccd5-b129-481c-b633-c9749307ac78.png) |
> feat: updates spot market order details format to follow derivative order details format

- app/data/aggregation.ts
- app/utils/constants.ts
- components/partials/common/orderbook/aggregation-selector.vue
- components/partials/derivatives/orderbook.vue
- components/partials/spot/orderbook.vue
- set custom aggregation for bnb, btc and eth markets.
- resolves FE-2
| BTC aggregation list | BNB aggregation list | WETH aggregation list |
|-----|-----|-----|
| ![image](https://user-images.githubusercontent.com/10151054/142979136-a5e1a002-f994-485e-b80c-c028a9dffeb2.png) | ![image](https://user-images.githubusercontent.com/10151054/142979186-4dffac41-61ec-4112-abd3-583613144cb2.png) | ![image](https://user-images.githubusercontent.com/10151054/142984526-f2538f7b-1b97-46c2-b776-ddf729e4e63d.png) |
> chore: set custom aggregation for bnb btc and eth markets

- components/partials/common/markets/table.vue
- locales/en.ts
- more information [here](https://linear.app/injective/issue/FE-282/dex-homepage-markets-display-daily-volume-of-all-markets) 
- resolves FE-282
> feat: display total volume (24 hr) of markets on homepage

- app/services/account.ts
- app/services/tokens.ts
- app/singletons/ExplorerCoinGeckoConsumer.ts
- components/partials/portfolio/holdings/index.vue
- store/account.ts
- store/portfolio.ts
- resolves #450 
- resolves FE-294
- the root cause of the issue is that we are relying on the bank balances data to retrieve the token metadata to reflect them in the subaccount page for optimization purposes, for example, if the user is holding ATOM in the subaccount but not on the injective chain (bank account). We won't be able to retrieve the tokenMeta data hence they are not displayed.
- I've added the logic to retrieve the sub balances token metadata only on the portfolio page load separately using the `api/explorer/v1/coin-price` API endpoint.
> fix: missing token balances on port folio page trading account holding section

- components/partials/derivatives/trading/trade.vue
- resolves #441 
- resolves FE-293
> fix: reward points for BNB/USDT perp always shows zero

- app/data/aggregation.ts
- app/utils/helpers.ts
- components/inputs/input.vue
- components/partials/derivatives/trading/trade.vue
- components/partials/spot/trading/trade.vue
- types/index.ts
- resolves FE-331 [linear](https://linear.app/injective/issue/FE-331/dex-market-order-input-min-quantity-tick-size-validation)
> fix: dex market order input - min quantity tick size validation

- app/data/dmm.ts
- app/services/dmm.ts
- components/partials/dmm/history/index.vue
- components/partials/dmm/ranking/elcs-row.vue
- components/partials/dmm/ranking/evcs-row.vue
- components/partials/dmm/summary/table-row.vue
- plugins/utils.ts
- store/dmm.ts
- hardcode dmm names for selected addresses
- prevent error toast from printing `dmm [inj14au322k9munkmx5wrchz9q30juf5wjgz2cfqku] didn't participate in the epoch [epoch_211228_220124]` messages
> chore: hardcode dmm names for selected addresses

- components/partials/derivatives/trading/trade.vue
- components/partials/spot/trading/trade.vue
This PR should resolve #537.
##Changes
Clicking `Market` or `Limit` in the `Trade` section of the `spot` and `derivatives` pages will now render the template associated with the selected option.
> chore: market / limit button toggling

- components/partials/common/derivatives/funding-payment.vue
- updates fund payment value to show up to 6 decimal places by default
> feat: fund payment show up to 6 decimal places by default

- app/utils/helpers.ts
- app/utils/input.ts
- components/inputs/input.vue
- components/layout/wallet/wallet.vue
- components/partials/derivatives/trading/trade.vue
- components/partials/modals/bridge/confirm.vue
- components/partials/portfolio/bridge/token-selector/select.vue
- components/partials/spot/trading/trade.vue
- types/index.ts
- resolves [FE-498](https://linear.app/injective/issue/FE-498/do-not-allow-scientific-notation-in-numeric-fields-or-handle-it-more)
- resolves [FE-499](https://linear.app/injective/issue/FE-499/impossible-to-overwrite-buy-amount-in-limit-trade)
- refactor numeric input key-up validation implementation
> feat: disable scientific notation in numeric fields

- components/partials/derivatives/trading/order-leverage.vue
- components/partials/derivatives/trading/trade.vue
About this PR: resolve https://github.com/InjectiveLabs/injective-dex/issues/672
toFixed() make 'x.0' become 'x' so that's why user can not enter input properly. So I assign this.form.leverage = leverage instead of .toFixed().
> fix: fixing decimal_leverage_input

- app/data/market.ts
- components/elements/empty-list.vue
- components/elements/table-body.vue
- components/partials/common/markets/markets.vue
- components/partials/markets/index.vue
- layouts/default.vue
- locales/market/en.ts
- resolves #688
- innovation list is configured based on the list provided [here](https://www.notion.so/injective/4e87d9197608449ca4d9b855d89f12bc?v=3f6a4eb3e56544f4997625b4606872df)
- ### Sort
- ### Search filter
- ### Category filter
- ### Stablecoin filter
- ### Type filter
- ### Empty list
> feat: implement standalone markets page business logic

- assets/css/components/_animate.scss
- components/elements/info-icon-tooltip.vue
- components/elements/market-info.vue
- components/partials/common/market/index.vue
- components/partials/common/market/last-traded-price-and-change.vue
- components/partials/common/market/next-funding.vue
- components/partials/common/market/stats.vue
- layouts/market.vue
- tailwind.config.js
- implements market page mobile stats
- figma [design](https://www.figma.com/file/qJtXzfX9nzh0c7yA6G9iI3/Injective-DEX?node-id=3940%3A7427)
- ### 375px
- ### 480px
- ### 640px
- ### 768px
- ### 1024px
- ### 1366px
> feat: market page mobile stats

- components/partials/derivatives/orderbook/order-book.vue
- locales/trade/en.ts
Closes #778 by adding the mark_price next to the last_traded_price inside the orderbook for derivatives.
> Show mark_price next to the last_traded_price in derivatives orderbook (#778)

- app/data/trading-view.ts
- removes wEth/usdt 4399.99 and 4399.999 price outliers
| Before | After |
|-------|-------|
| <img width="752" alt="image" src="https://user-images.githubusercontent.com/10151054/168781807-09090dc4-6759-4e78-9f78-b8a6c89452b2.png"> | <img width="754" alt="image" src="https://user-images.githubusercontent.com/10151054/168781701-38320ce0-0bd6-4ca5-a912-816a00a212be.png"> |
> chore: weth usdt remove price outliers

- components/trading-view/datafeed/datafeed.ts
- did a deep dive into the trading view implementation and it seems that the [getBars()](https://github.com/InjectiveLabs/injective-dex/blob/ef11d412fa8adccb446c8b5a764989e210e5b5de/components/trading-view/datafeed/datafeed.ts#L150) function cannot differentiate between `1D`, `7D` or `30D`.
- The resolution is always returned as `D`, hence the [periodLengthSeconds](https://github.com/InjectiveLabs/injective-dex/blob/ef11d412fa8adccb446c8b5a764989e210e5b5de/components/trading-view/datafeed/data-pulse-provider.ts#L109) function are not returning the correct calculation. 
- on a separate note, BE is treating `D` as `1D` by default, confirmed by @vinhphuctadang.
- Seems like the [charting_library repo](https://github.com/tradingview/charting_library/wiki/UDF) is deprecated, in the meantime, …
> fix: trading view remove 7D and 30D resolutions from selection list

- components/partials/derivatives/trading/order-details-market.vue
- components/partials/derivatives/trading/order-details.vue
- components/partials/spot/trading/order-details-market.vue
- components/partials/spot/trading/order-details.vue
This PR temporarily hides the expected pts. field from the trade details as was requested in #880.
> chore: hide expected pts. field from trade details

- components/partials/common/elements/number.vue
- components/partials/common/trade/trade.vue
This PR closes part of #368.
The modified regex will now also support negative numbers.
> Preserve negative sign for trade history fees #368

- store/token.ts
This PR:
resolves UI not subtracting bridgeFee from bridgeAmount resulting in error:
```rpc error: code = InvalidArgument desc = failed to execute message; message index: 0: 
48490000000000000000peggy0x4d224452801ACEd8B2F0aebE155379bb5D594381 is smaller than 
50604164904862579281peggy0x4d224452801ACEd8B2F0aebE155379bb5D594381: insufficient funds: invalid request
```
> fix: ethereum withdrawal transaction max amount

- app/utils/market.ts
This PR fixes #910, we were using the incorrect variable when comparing numbers `> 1000` and `< 1000000`
> fix: fixed bug in getAbbreviatedVolume helper

- components/partials/portfolio/bridge/token-selector/select.vue
This PR closes #911, for bridging network logos we should not use the `getTokenLogoWithVendorPrefix` helper since the images are located in the static folder of this repo.
> Fix for broken Bridge token logo after TokenSelector modifications

- components/partials/fee-discounts/staked-amount.vue
This PR fixes #927 by using default rounding on the `stakedAmount` before rendering.
> fix: fee discounts page - round up stakedAmount to two decimal places

- components/partials/common/derivatives/funding-payment.vue
This PR fixes #930. It removes special handling for negative numbers as it is no longer needed because `number.vue` already handles negative numbers properly after #897.
> fix: prevent double negative sign for negative funding payments
